apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: container-build

on:
  workflow_call:
    inputs:
      appName:
        type: string
        required: true
      imageNamespace:
        type: string
        required: false
        default: "hackers-app"
      versionStart:
        type: string
        required: false
        default: "3.0"
      repo:
        type: string
        required: true

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        with:
          repository: ${{ inputs.repo }}

      - name: Setup AWS API authentication
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: "1200"
          role-to-assume: ${{ vars.IMAGE_BUILDER_AWS_ROLE_ARN }}

      - uses: cloudbees-io/kaniko@v1
        name: Build container image
        kind: build
        with:
          destination: ${{ vars.ECR_REGISTRY }}/${{ inputs.imageNamespace }}/${{ inputs.appName }}:${{ inputs.versionStart }}-${{ cloudbees.version }}
          tar-path: container-image.tar
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          artifact-name: ${{ inputs.appName }}

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Built and pushed image to ECR

            [ECR](https://${{ vars.ECR_REGISTRY }}/${{ inputs.imageNamespace }}/${{ inputs.appName }}/tags)

            Published ${{ vars.ECR_REGISTRY }}/${{ inputs.imageNamespace }}/${{ inputs.appName }}:${{ inputs.versionStart }}-${{ cloudbees.version }}
          format: MARKDOWN
